const cards = [
    {
        id: 1,
        type: "A", 
        name: "LUFFY",
        akuma: true,
        determination: 10,
        attack: 8,
        intellect: 2,
        img: "/assets/luffy.jpg",
    },
    {
        id: 2,
        type: "A", 
        name: "ZORO",
        akuma: false,
        determination: 8,
        attack: 10,
        intellect: 3,
        img: "/assets/zoro.jpg",
    },
    {
        id: 3,
        type: "B", 
        name: "CHOPPER",
        akuma: true,
        determination: 7,
        attack: 7,
        intellect: 7,
        img: "/assets/chopper.jpg",
    },
    {
        id: 4,
        type: "A", 
        name: "ROBIN",
        akuma: true,
        determination: 6,
        attack: 10,
        intellect: 9,
        img: "/assets/robin.jpg",
    },
    {
        id: 5,
        type: "C", 
        name: "NAMI",
        akuma: false,
        determination: 7,
        attack: 3,
        intellect: 10,
        img: "/assets/nami.jpg",
    },
    {
        id: 6,
        type: "C", 
        name: "USOPP",
        akuma: false,
        determination: 5,
        attack: 4,
        intellect: 10,
        img: "/assets/usopp.jpg",
    },
    {
        id: 7,
        type: "B", 
        name: "SANJI",
        akuma: false,
        determination: 8,
        attack: 8,
        intellect: 6,
        img: "/assets/sanji.jpg",
    },
]
